wire: cache the non-witness serialization of MsgTx to memoize part of…
btcsuite/btcd pull request #1376
Opened 2019-01-19 00:04 UTC by Roasbeef

… TxHash

In this commit, we add a new field to the `MsgTx` struct:
`cachedSeralizedNoWitness`. As we decode the main transaction, we use an
`io.TeeReader` to copy over the non-witness bytes into this new field.
As a result, we can fully cache all tx serialization when computing the
TxHash. This has been shown to show up on profiles during IBD. Caching
this value allows us to optimize TxHash calculation across the entire
daemon as a whole.

2019-01-19 03:48 UTC, Roasbeef commented
There's a bug here in that it doesn't detect mutations in the underlying `*wire.MsgTx` so if the value is changed at all, then we don't update the serialization. In the current pipeline for block validation, this doesn't manifest, but some of our tests do this which introduces some of the new failures in Travis.

2020-03-04 13:55 UTC, jakesyl commented
@jcvernaleo (as per #1530)
- Low priority
- Outdated (needs updates to be merged)

2023-03-13 23:42 UTC, Roasbeef commented
Here's a recent run late in the chain: 

![Screenshot 2023-03-13 at 4 40 00 PM](https://user-images.githubusercontent.com/998190/224855953-f0d923c0-9ae8-465c-9407-f05467648b82.png)

From this we can see that when checking signatures, we actually spend most of our time just encoding the tx again to compute the _sighash_. 

Here's a flame graph for another view: 

![Screenshot 2023-03-13 at 4 42 30 PM](https://user-images.githubusercontent.com/998190/224856068-11450830-80ef-4250-9eb3-f4e8c888528d.png)

cc @kcalvinalvin

2023-03-14 06:16 UTC, kcalvinalvin commented
I need a refresher on this but if memory serves right, doing away with the channel stuff in binaryFreeList and using a sync.Pool got rid of a big chunk of the time taken.

> From this we can see that when checking signatures, we actually spend most of our time just encoding the tx again to compute the sighash.

But yeah if this is something that doesn't need to happen in the first place with memoization that'd be much better.

2023-08-09 23:46 UTC, Roasbeef commented
Recent observation of the impact here: 
![Screenshot 2023-08-09 at 4 45 09 PM](https://github.com/btcsuite/btcd/assets/998190/5391a9c8-ab02-40c8-b044-cbcf27861ab1)

2023-08-09 23:48 UTC, Roasbeef commented
Related PR re binary free list: https://github.com/btcsuite/btcd/pull/1426

2023-11-16 01:40 UTC, Roasbeef commented
Rebased!

2023-12-05 02:39 UTC, Roasbeef commented
Dug a bit, and I realize the issue is in the test itself, it mutates transactions, with stuff like `replaceSpendScript`. So what we need here (for the test's sake) is that we have a method to wipe the cached serialization if something is mutated. Alternatively, we have some internal map that uses the `MsgTx` as a value, which is consulted to see if the transaction has changed since last time.

2023-12-05 02:47 UTC, Roasbeef commented
Pushed a tx implementing the above, don't think it's ideal though...worried about weird edge cases where transaction generation code uses a tx as a scratch pad and makes multiple versions to sign, with this it'll give the wrong `txid` after the first instance. 

Also added a commit that'll re-use the non-witness serialization for `SerializeNoWitness`.

2023-12-08 17:50 UTC, Crypt-iQ reviewed
I looked in both btcd and lnd to see if we modify `wire.MsgTx` after calculating the hash, but couldn't find any instances. The code looks good, but I think we need to be extra careful and see if there are any instances across our codebases

2023-12-12 12:25 UTC, guggero requested changes
While I like the elegance of using a `io.TeeReader` (TIL by the way), I'm not sure if this would break a bunch of things outside of `btcd`, namely in `lnd` and related projects.

What if we make the caching optional with an additional struct member boolean (or if memory footprint is a concern, use a bit within the `Version` field) that turns the caching on?
That way we could both benefit from the optimization within `btcd` while not breaking any assumptions for outside code.

2023-12-12 12:25 UTC, guggero commented on wire/msgtx.go
> +	if WriteVarInt(&rawTxBuf, pver, count); err != nil {
Need to add `err := WriteVarInt()`.

2023-12-12 12:25 UTC, guggero commented on wire/msgtx.go
> +	// series after the versino of segwit transactions.
nit: s/versino/version

2023-12-12 12:25 UTC, guggero commented on wire/msgtx.go
> +	cachedSeralizedNoWitness []byte
nit: s/cachedSeralizedNoWitness/cachedSerializedNoWitness/

2023-12-12 12:25 UTC, guggero commented on wire/msgtx.go
> +	msg.cachedSeralizedNoWitness = nil
Don't we also need to call this in the helper methods like `AddTxIn()` and `AddTxOut()`? Or is the assumption that `TxHash()` would in practice only be called once the transaction is fully built, so the cache doesn't need to be invalidated?

I'm mostly worrying about uses of `MsgTx` outside of `btcd`, where I'm not sure we can 100% guarantee that we're always using this pattern...

2023-12-13 03:04 UTC, Roasbeef commented
> What if we make the caching optional with an additional struct member boolean (or if memory footprint is a concern, use a bit within the Version field) that turns the caching on?


Not a bad idea, agree that this could have a lot of unintended consequences. The other approach uses `btcutil.Tx` which gives another route to implement something like this.

2023-12-16 00:10 UTC, Roasbeef commented
Closing in favor of #2023, see this comment for some details: https://github.com/btcsuite/btcd/pull/2023#issuecomment-1858625556

TL;DR: I think we need to remove/optimize the binary free list instead.

2023-12-16 00:10 UTC, closed without merging