Added ListSinceBlockMinConfWatchOnly method.
btcsuite/btcd pull request #1451
Opened 2019-07-16 16:54 UTC by nalcheg

2020-03-04 13:35 UTC, jakesyl commented
@jcvernaleo (as per #1530)

- Low priority
- Enhancement

2020-06-13 21:08 UTC, onyb commented on rpcclient/wallet.go
> +	}
This probably won't work if you want to do something like _list all watch-only transactions_ with the following call:
```
ListSinceBlockMinConfWatchOnlyAsync(nil, 1, true)
```

Here's a workaround, although I'm not sure if it's the best solution.

```suggestion
	} else {
	        hash = btcjson.String("")
	}
```

2020-09-08 14:26 UTC, nalcheg commented
did in https://github.com/btcsuite/btcd/pull/1163

2020-09-08 14:29 UTC, onyb commented
@nalcheg #1163 is not doing the same thing. You added `ListSinceBlockMinConfWatchOnlyAsync`. That one was about `ListTransactionsCountFromWatchOnlyAsync`.

2020-09-08 15:08 UTC, nalcheg commented
sorry, I was wrong

2020-09-08 15:16 UTC, onyb commented on rpcclient/wallet.go
> +	}
Thanks to https://github.com/btcsuite/btcd/pull/1594, we may not need to do this. Could you please verify this on your side?

2020-09-08 15:16 UTC, onyb requested changes
Needs a rebase + the small test I suggested.

2020-09-08 16:54 UTC, onyb requested changes
Could you please add the following unit-test to `walletsvrcmds_test.go`? (line 710)

```go
		{
			name: "listsinceblock pad null",
			newCmd: func() (interface{}, error) {
				return btcjson.NewCmd("listsinceblock", "null", 1, false)
			},
			staticCmd: func() interface{} {
				return btcjson.NewListSinceBlockCmd(nil, btcjson.Int(1), btcjson.Bool(false))
			},
			marshalled: `{"jsonrpc":"1.0","method":"listsinceblock","params":[null,1,false],"id":1}`,
			unmarshalled: &btcjson.ListSinceBlockCmd{
				BlockHash:           nil,
				TargetConfirmations: btcjson.Int(1),
				IncludeWatchOnly:    btcjson.Bool(false),
			},
		},
```

2020-09-09 14:10 UTC, onyb approved these changes
Looks great! Thanks for your contribution.

2020-09-14 13:48 UTC, jcvernaleo approved these changes
OK

2020-09-14 13:48 UTC, merged