Improve gc for isunspendable method
btcsuite/btcd pull request #1615
Opened 2020-08-15 01:47 UTC by Rjected

Through profiling, I've found that the `IsUnspendable` method is a large source of allocations during the sync process.

In an effort to reduce the allocations made by this method, and in the sync process overall, I've simply removed the part of `parseScriptTemplate` which allocates and appends to an array (which never ends up being used by `IsUnspendable`) and pointed `IsUnspendable` to that method, called `checkScriptTemplateParseable`.

To show that this actually did reduce the allocations (and runtime) of the `IsUnspendable` method, I've created a benchmark and run it on both versions of the code, once on the [`e761244`](https://github.com/btcsuite/btcd/commit/e7612446051c390a4372d7604029b1eaff8a7f1d) commit, and once on the [`0963732`](https://github.com/btcsuite/btcd/commit/096373242c26946aabaf87f554003675aed6dfcd) commit.
I used the command on the older commit:
```
go test -v -bench=BenchmarkIsUnspendable -run=^\$ -benchmem -benchtime 10s -count 30 >> ~/unspendableold.txt
```
I then used this command on the newer commit:
```
go test -v -bench=BenchmarkIsUnspendable -run=^\$ -benchmem -benchtime 10s -count 30 >> ~/unspendablenew.txt
```

After running these, `benchstat` yielded the following result:
```
name             old time/op    new time/op    delta
IsUnspendable-8     283ns ± 3%      47ns ± 2%  -83.34%  (p=0.000 n=28+27)

name             old alloc/op   new alloc/op   delta
IsUnspendable-8      768B ± 0%       32B ± 0%  -95.83%  (p=0.000 n=30+30)

name             old allocs/op  new allocs/op  delta
IsUnspendable-8      1.00 ± 0%      1.00 ± 0%     ~     (all equal)
```
The benchtime and count in my benchmarks are unnecessarily high, I get similar results with a lower count and deleted benchtime parameter:
```
go test -v -bench=BenchmarkIsUnspendable -run=^\$ -benchmem -count 10 >> ~/unspendablenew.txt
```

This shows that in at least my benchmarks, the allocations and runtime of this method were significantly reduced.
In the future we should definitely backport changes from [dcrd #1656](https://github.com/decred/dcrd/pull/1656) (I will make an issue for this), but that would be a massive PR to consensus critical code, would likely need to be adapted, and the improvements for this method seem good enough for a single, easily reviewable PR.
The point of this PR is to:
1. Improve allocations of `IsUnspendable`.
2. Show that there is significant work to be done on the `txscript` package, and it would go a very long way towards improving the sync time if we focus on performance using benchmarking and profiling tools.

This is a draft right now because a test isn't passing but this will be fixed soon.

Backporting the benchmark changes would be a great future addition in itself, and hopefully this PR highlights this.

2020-08-19 02:59 UTC, Rjected commented
New benchmark results for commit [`b085b02`](https://github.com/btcsuite/btcd/commit/b085b029df29bf75917ac7de762b51ca0eacda18):
```
name             old time/op    new time/op    delta
IsUnspendable-8     283ns ± 3%       9ns ± 1%   -96.82%  (p=0.000 n=28+28)

name             old alloc/op   new alloc/op   delta
IsUnspendable-8      768B ± 0%        0B       -100.00%  (p=0.000 n=30+30)

name             old allocs/op  new allocs/op  delta
IsUnspendable-8      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=30+30)
```
Since the tests also pass now, I'll make this a non draft. I'd also like to note that the benchmark is not an authoritative measure of performance. We should build stuff that helps build benchmarks which represent more of a real world load, take these results with a grain of salt!

2020-09-07 10:51 UTC, onyb requested changes
utACK. Good find and quite clever. 👍

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +// Not returning the full opcode list up until failure also has the benefit of
You probably want an additional new line here.

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +	}
Isn't this already taken care of by the following two lines?

```go
var firstOpcode byte = OP_0
var numParsedInstr uint = 0
```

The comment still deserves a mention.

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +	var firstOpcode byte = OP_0
This feels like a misuse of `OP_0`. If I understand correctly, using any opcode will work here as long as it is not `OP_RETURN`.

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +	return numberOfPops > 0 && firstOpcode == OP_RETURN
How about using `(*byte, error)` as the return type of `checkScriptTemplateParseable`? The check would simply then be:

```go
firstOpcode, err := checkScriptTemplateParseable(pkScript, &opcodeArray)
if err != nil {
         return true
}

return firstOpcode != nil && *firstOpcode == OP_RETURN
```

This takes into account my other remark that if the script is empty, it doesn't make sense for the first opcode to be `OP_0`.

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +	// Not provably unspendable
Is this necessary? It appears to me that it is already taken care of in `checkScriptTemplateParseable`.

2020-09-07 10:51 UTC, onyb commented on txscript/script_test.go
> +			pkScript: []byte{0x6a},
```suggestion
			pkScript: []byte{OP_RETURN},
```

2020-09-07 10:51 UTC, onyb commented on txscript/script_test.go
> +			pkScript: []byte{0x51},
```suggestion
			pkScript: []byte{OP_TRUE},
```

2020-09-07 10:51 UTC, onyb commented on txscript/script_test.go
> +			pkScript: []byte{0xa9, 0x14, 0x82, 0x1d, 0xba, 0x94, 0xbc, 0xfb,
Whenever possible, it's nice to use human-friendly names for the opcodes. It's not necessary in this example, but I added some suggestions for the other test cases you added.

2020-09-07 10:51 UTC, onyb commented on txscript/script.go
> +		// Parse data out of instruction.
The entire `switch` block appears to be duplicated in `parseScriptTemplate`. Do you think it's worth doing a refactoring?

2020-09-08 14:03 UTC, jcvernaleo reviewed
Looks great but needs to address @onyb's comments then it can go in.

2020-11-03 14:44 UTC, jcvernaleo commented
I think this needs to be rebased for the proper checks too.

2021-01-26 15:03 UTC, jcvernaleo commented
@onyb could you take another look at this one to see if your comments were addressed?

2021-02-02 14:17 UTC, onyb approved these changes

2021-02-02 14:18 UTC, jcvernaleo approved these changes
Looks good to me too now.
OK

2021-02-02 14:20 UTC, merged