Fix getmininginfo unmarshal error
btcsuite/btcd pull request #1644
Opened 2020-10-04 01:28 UTC by DavidMazary

Since JSON doesn't distinguish between ints and floats in its number type, Go will fail to decode valid integers in scientific notation as noted in #1458 

1. Added a unit test for this condition that fails before the fix and passes after
2. Verified that output values and format were unchanged when running `btcctl getmininginfo`

2020-10-04 01:35 UTC, jakesyl commented
can you rebase into a single commit?

2020-10-08 18:12 UTC, onyb approved these changes
Congratulations on your first PR to btcd!  🎉

2020-10-08 18:13 UTC, onyb commented
@DavidMazary Just needs a rebase to fix the merge conflicts.

2020-10-12 13:53 UTC, jcvernaleo commented
Just fix the conflict and this is good to go in!

2020-10-19 13:37 UTC, jcvernaleo approved these changes
OK

2020-10-19 13:37 UTC, jcvernaleo requested changes
Fix merge conflicts and then this is good to go.

Thanks!

2020-10-21 13:47 UTC, DavidMazary commented
Fixed merge conflicts!

2020-10-26 13:32 UTC, jcvernaleo approved these changes
OK

2020-10-26 13:33 UTC, merged