rpcclient: add more wallet commands
btcsuite/btcd pull request #1645
Opened 2020-10-06 12:29 UTC by torkelrogstad

Implement backupwallet, dumpwallet, loadwallet and unloadwallet.

2020-10-08 18:19 UTC, onyb requested changes
Looks good. Just needs some cosmetic changes.

2020-10-08 18:19 UTC, onyb commented on btcjson/walletsvrcmds.go
> +	MustRegisterCmd("backupwallet", (*BackupWalletCmd)(nil), flags)
Let's sort these in alphabetic order.

2020-10-08 18:19 UTC, onyb commented on rpcclient/wallet.go
> +func (c *Client) BackupWallet(destination string) error {
Needs a comment.

2020-10-09 12:37 UTC, torkelrogstad commented
@onyb I've addressed your comments.

2020-10-09 13:11 UTC, onyb approved these changes

2020-10-10 12:13 UTC, onyb requested changes
My previous review was not so thorough, so here's a second pass.

2020-10-10 12:13 UTC, onyb commented on rpcclient/wallet.go
> +func (c *Client) UnloadWallet(walletName string) error {
⚠️ `walletName` must be optional.

If the RPC server URL already contains the name of the wallet, like `http://127.0.0.1:8332/wallet/<walletname>`, it'll return an error.

From the docs:
> Specifying the wallet name on a wallet endpoint is invalid.

2020-10-10 12:13 UTC, onyb commented on rpcclient/wallet.go
> +	_, err := receiveFuture(r)
What if someone is interested in the result, which may have useful information like "warnings"?

2020-10-10 12:13 UTC, onyb commented on rpcclient/wallet.go
> +	_, err := receiveFuture(r)
The result may not contain the same `destination` as the input, so we should not ignore it.

2020-10-19 13:38 UTC, jcvernaleo commented
Agreed with @onyb's comments then this one will be good to go in.

2020-10-20 07:36 UTC, torkelrogstad commented
@onyb @jcvernaleo I've addressed your comments!

2020-10-20 08:34 UTC, onyb approved these changes

2020-10-26 13:34 UTC, jcvernaleo approved these changes
Looks all good now!
OK

2020-10-26 13:34 UTC, merged