wire+chaincfg: add signet params
btcsuite/btcd pull request #1692
Opened 2021-02-14 14:51 UTC by guggero

This commit adds all necessary chain parameters for connecting to the
public signet network.
Reference: https://github.com/bitcoin/bitcoin/pull/18267

Needed for adding signet support to `lnd`.
Replaces #1536.

cc @Roasbeef, @cfromknecht.

2021-02-16 22:56 UTC, alexbosworth commented on config.go
> +			"four"
Remove segnet or change to five?

2021-03-05 08:45 UTC, guggero commented
cc @wpaulino

2021-03-10 12:09 UTC, guggero commented on chaincfg/params.go
> +	sigNetPowLimit = new(big.Int).Lsh(new(big.Int).SetInt64(0x0377ae), 212)
Hmm, it looks like I just miscounted a zero there. Good catch!

2021-03-10 12:12 UTC, guggero commented on chaincfg/params.go
> +	RelayNonStdTxs: true,
I wasn't sure about this either. But seems logical to set this according to `fRequireStandard` (or its inverse value). Set it to `false`.

2021-03-10 12:13 UTC, guggero commented on chaincfg/params.go
> +	ReduceMinDifficulty:      true,
Also wasn't sure here. But makes sense to set this to false.

2021-03-10 22:42 UTC, wpaulino approved these changes

2021-03-13 00:18 UTC, Roasbeef requested changes
How about the ability to configure a signet target at runtime? Otherwise if people want to make their own custom signets (which I think is the whole point?), then they'd need to recompile and distribute their binaries, vs being able to say: "yo use these params to join my signet that has covenants implemented".

2021-03-13 00:24 UTC, Roasbeef commented on chaincfg/params.go
> +		DeploymentTaproot: {
Shouldn't we scope this signet as the "public taproot" signet?

2021-03-15 15:33 UTC, guggero commented
@Roasbeef I added the changes necessary to connect to a custom signet. I wasn't able to spin one up locally, but I'll test this as soon as I'm successful.

2021-03-22 17:33 UTC, guggero commented
I've verified that syncing a `btcd` node against both the "public taproot signet" and a custom local signet work.

Example for connecting to a custom local signet (using `bitcoind`, see script below):
```
btcd --signet --signetchallenge=512103e5602bf0701c1565a89695eb618c3d652b0532464dbfca6130c659c06dfc11fd51ae --signetseednode=127.0.0.1 --listen=:38666 --rpclisten=:38662 --rpcuser=lightning --rpcpass=lightning
```

Client:
```
btcctl --signet --rpccert ~/.btcd/rpc.cert --rpcuser=lightning --rpcpass=lightning --rpcserver=localhost:38662
```

Here's my script I used to spin up my own signet (must run inside the `src` directory of the `bitcoin` source code with the current master compiled): https://pastebin.com/YJKAPM0p

2021-04-22 11:05 UTC, guggero commented
@Roasbeef PTAL, would be nice to include this in the next `lnd` release.

2021-04-23 20:05 UTC, Roasbeef approved these changes
Thanks for making the signet configuration more flexible! I have some things in mind that would be really dope to expose using a new public signet 😈

2021-04-23 20:06 UTC, Roasbeef commented
@guggero tried to click on that pastebin link but it's expired, if you recall what it was, can you re-host it somewhere? Thanks!

2021-04-23 20:13 UTC, Roasbeef requested changes
Actually re-visiting the BIP, this doesn't appear to allow creation of a "custom" signet as no new logic to validate the new block commitment nor the challenge signature has been added. Is the intent here just to add a "light" minimally validating signet client in the short term before following up w/ the proper block generation and validation logic?

2021-04-26 18:01 UTC, Roasbeef approved these changes
Chatted w/ Oliver offline and determined that we'll merge this "light client" functionality, then later follow up with the fully logic needed to produce and verify signet blocks so new public btcd based signets will be possible in the future.

2021-04-26 18:01 UTC, merged