rpctest: ensure rpclisten is set to an available port
btcsuite/btcd pull request #1806
Opened 2022-02-07 18:19 UTC by arshbot

Replaces the implementation of `generateListeningAddresses` to use `NextAvailablePort` from lntest. Would have imported directly, however this creates a circular dependency.

2022-02-09 11:17 UTC, carlaKC requested changes
I think that we can skip these changes and just set `ListenAddressGenerator` as done in [lnd](https://github.com/lightningnetwork/lnd/blob/61bffa70f96d58ae06edd18bc763f4e739c53638/lntest/itest/lnd_test.go#L100)?

2022-02-09 11:17 UTC, carlaKC commented on integration/rpctest/rpc_harness.go
> +	ListenerFormat = "127.0.0.1:%d"
would rather just make this `host = "127.0.0.1"`?

2022-02-10 08:20 UTC, carlaKC commented
> Disagree, that's a bandaid for this upstream issue. I don't mind having that fix as well, but `rpclisten` shouldn't just be set to a random port without testing.

Totally! Worth fixing here so that we don't need the workaround, but in the meantime this doesn't need to block downstream.

2022-02-10 08:20 UTC, carlaKC approved these changes
Looks good!

2022-04-09 11:25 UTC, jcvernaleo approved these changes
OK

2022-04-09 11:25 UTC, merged