Added test for client.GetChainTxStatsAsync() in rpcclient.
btcsuite/btcd pull request #2049
Opened 2023-10-26 15:46 UTC by ClaytonNorthey92

Added test for client.GetChainTxStatsAsync() in rpcclient.  This sets up a test websocket server to run the tests.  Also, ensure these are run within a timeout, since they rely on concurrency.

Similar to [this other pull request](https://github.com/btcsuite/btcd/pull/2048), these changes increase the code coverage for rpcclient tests to 5.3%

```bash
go-acc ./rpcclient/
ok  	github.com/btcsuite/btcd/rpcclient	0.255s	coverage: 5.3% of statements in ./rpcclient/
```

2023-11-01 20:54 UTC, jcvernaleo requested changes
Love the addition of a test but looks like the actions are failing.

Could you fix those please?

2023-11-01 21:24 UTC, ClaytonNorthey92 commented
Hey @jcvernaleo , my apologies, I had forgotten to add [the websocket module to btcutil/go.sum](https://github.com/btcsuite/btcd/pull/2049/files#diff-de0481f45577ff4f0c8941971f9610f06219c7657c13333f63780714e29898edR37), resulting in errors from `btcutil` in the pipeline.

errors found [here](https://github.com/btcsuite/btcd/actions/runs/6656561784/job/18278199875#step:4:122) and [here](https://github.com/btcsuite/btcd/actions/runs/6656561784/job/18278199584#step:4:12986) both result from that not being found in the `go.sum` file.

I have run both `make unit-race` and `make unit-cover` locally with this fix, they both work.  I think this is good to re-run the pipelines 🤞

2023-11-02 19:19 UTC, jcvernaleo requested changes
OK

Code looks good but there is a conflict after the previous PR went in.  If you could fix conflict, I'll approve and merge.

Sorry about that!

2023-11-02 20:02 UTC, ClaytonNorthey92 commented
Hey @jcvernaleo , I just rebased and pushed, everything should be up-to-date now 👍 thanks!

2023-11-02 20:16 UTC, jcvernaleo approved these changes
OK

2023-11-02 20:16 UTC, merged