blcokchain: Add ReconsiderBlock()
btcsuite/btcd pull request #2181
Opened 2024-04-30 10:51 UTC by kcalvinalvin

Adds `ReconsiderBlock()` on blockchain that will clear up any block validation statuses and re-validate the block. If the block is part of a longer chain, then the chain will reorganize to that chain.

Depends on #2155

2024-05-09 01:08 UTC, BrannonKing commented
I just want to note that the InvalidateBlock/ReconsiderBlock in lbcd and and bchd is incorrect. See https://github.com/gcash/bchd/issues/512

2024-05-22 20:16 UTC, Roasbeef commented
Can be rebased now!

2024-05-23 04:02 UTC, kcalvinalvin commented
> I just want to note that the InvalidateBlock/ReconsiderBlock in lbcd and and bchd is incorrect. See [gcash/bchd#512](https://github.com/gcash/bchd/issues/512)

This is a completely independent implementation by me. I didn't even know they were implemented there.

2024-05-23 23:04 UTC, Roasbeef commented on blockchain/chain.go
> +		}
Can't we break after this?

Also isn't it possible that the block we want to reconsider is a descendent of _several_ of the inactive chain tips? If this is the case, then we'll continually re-assign `reconsiderTip` for each of them. 

Consider a scenario where we had 3 inactive chain tips `{A, B, C}`, block `D` that we want to reconsider is a descendent of all 3 chain tips, but they later on fork further down the line produce distinct chain tips (that we thought were invalid in the past).

2024-05-23 23:04 UTC, Roasbeef commented on blockchain/chain.go
> +		return nil
Should log the error here.

2024-05-23 23:08 UTC, Roasbeef commented on blockchain/chain.go
> +		}
Actually on second thought, block hash chains are unique, so if `D` is a descendent of all 3 chain tips, then the chain tips should themselves be identical.

2024-05-23 23:11 UTC, Roasbeef requested changes

2024-05-23 23:11 UTC, Roasbeef commented on blockchain/chain.go
> +
`log.Infof("Reconsidering block_hash=%x", hash[:])`

2024-05-23 23:11 UTC, Roasbeef commented on blockchain/chain.go
> +
`log.Debugf("Examining %v inactive chain tips for reconsideration")`

2024-05-23 23:11 UTC, Roasbeef commented on blockchain/chain.go
> +	// We're checking if the reorganization that'll happen is actually valid.
```
log.Infof("Re-org to reconsider_block=%x size %v (num_add=%v, num_detach=%v)", reconsiderTip.hash[;], len(detchNodes)+len(attachNodes), len(detchNodes), len(attachNodes))
```

2024-06-19 05:59 UTC, kcalvinalvin commented
Closing in favor of #2196

2024-06-19 05:59 UTC, closed without merging