peer, main, netsync, blockchain: parallel block downloads
btcsuite/btcd pull request #2226
Opened 2024-08-07 11:35 UTC by kcalvinalvin

This PR modifies `netsync.Manager` so that all the header-first blocks downloaded before the last checkpoint is done out of order by utilizing `query.WorkManager` from neutrino.

Gonna put it in draft for now as testing is sorta difficult and I'm not convinced it's downloading blocks faster for mainnet. By my testing it works just fine in testnet but mainnet seems to be slow when downloading blocks. Still identifying where the bottleneck is and will make adjustments accordingly.

If anyone else would like to give this a try please let me know if you see speed ups or slow downs from this PR.

2024-08-08 07:55 UTC, kcalvinalvin commented
Seems like the slowdowns are coming from a single peer that's slowing down the block processing. `peerWorkManager` having capabilities to completely disconnect a peer would help in this.

2024-08-13 02:06 UTC, Roasbeef commented
> Seems like the slowdowns are coming from a single peer that's slowing down the block processing. peerWorkManager having capabilities to completely disconnect a peer would help in this.

Interesting, is the issue that the single peer is assigned blocks uniformly and is always the last one to send (haven't looked in PR at detail yet). I have this tracking issue in the `neutrino` repo for adding stuff like dynamic tuning, better work assignment, and also work stealing. With work stealing, the faster peers would steal the block request from the work queue of the slow peer, with faster peers helping us to be as slow as the fastest peer.

2024-10-03 15:26 UTC, saubyk commented
cc: @Crypt-iQ @ProofOfKeags for review

2025-02-17 05:56 UTC, kcalvinalvin commented
Pushed all the code that I have and updated the original comment with extra information

2025-04-10 14:33 UTC, saubyk commented
cc: @starius for review

2025-04-17 22:38 UTC, yyforyongyu reviewed
Fantastic feature! I need a second round to load all the context to dive deeper. As for now I think for new code we should have unit tests. Meanwhile is the dependent PR ready for review? I saw it’s draft stage. https://github.com/lightninglabs/neutrino/pull/308

2025-04-17 22:38 UTC, yyforyongyu commented on netsync/manager.go
> +	for i, sub := range sm.peerSubscribers {
i think we can use a map instead for `peerSubscribers`

2025-04-17 22:38 UTC, yyforyongyu commented on netsync/manager.go
> +		// Keep fetching until we don't have an error.
Can we really do this? Is it safe?

2025-04-17 22:38 UTC, yyforyongyu commented on netsync/manager.go
> +func (sm *SyncManager) ConnectedPeers() (<-chan query.Peer, func(), error) {
I think we should name it to sth else, it's confusing to see three `ConnectedPeers` defined in the repo, maybe `SubscribePeers`.

2025-04-17 22:38 UTC, yyforyongyu commented on netsync/manager.go
> +		if sm.chainParams != &chaincfg.RegressionNetParams {
In this case I think it's the tests should be updated, not the code, otherwise we cannot cover the branch here in our tests.

2025-04-21 15:40 UTC, kcalvinalvin commented on netsync/manager.go
> +	if !sm.current() && !isSyncCandidate {
Oh hmm good point. In the case of when we're IBD-ing this doesn't matter but this will still disconnect peers that may try to sync off of us.

I'll address this later with other changes.

2025-05-12 15:56 UTC, kcalvinalvin commented
There were some git hell that I had to figure out of... Lost some of my code.

The latest push is good and depends on https://github.com/lightninglabs/neutrino/pull/308

2025-05-13 00:15 UTC, saubyk commented
cc: @mohamedawnallah for review

2025-05-20 01:49 UTC, mohamedawnallah commented
Thanks @kcalvinalvin for the PR, I will review it by the end of this week 🙏

2025-05-20 03:19 UTC, yyforyongyu requested changes
Comments from the previous round are not addressed, maybe due to this?
> There were some git hell that I had to figure out of... Lost some of my code.

My main comments are,
- would be nice to split the PR into at least two parts, so it's easier to review and we can have faster merges,
  - the first part deals with the split of processing block msgs based on `headersFirstMode`
  - the second part deals with the connection handling and parallel block queries (maybe they should be their own PRs)
- please add unit tests, given IBD is extremely critical.

I'm still in the process of digesting the IBD process, tho this PR is mainly about speeding up the checkpointed blocks (also just learnt that we don't have `assumevalid` in btcd yet...). My main question is whether it's possible for the remote peer to trick us into using `BFFastAdd` flag for blocks beyond checkpoints, will dig.

2025-05-20 03:19 UTC, yyforyongyu commented on netsync/manager.go
> -	delete(state.requestedBlocks, *blockHash)
Removing this check creates a DoS vector as the peer can now keep sending us orphan blocks to fill up the memory used by `b.orphans`.

2025-05-20 03:19 UTC, yyforyongyu commented on netsync/manager.go
> +		if err != nil {
I think there exists a DoS vector that the peer can send us the same orphan block twice and shut down our node.

2025-06-03 08:17 UTC, kcalvinalvin commented on netsync/manager.go
> +		// Keep fetching until we don't have an error.
So `query.WorkManager` is designed around downloading the entire GetData request. This works well for block headers or cfilters but not really for blocks since we verify as they come in.

I wanted to have a guarantee that when you call `queueFetch`, you'll get all the blocks in that request. `queueFetch` will call a new query to `query.WorkManager` which will try to peers to download from.

This seemed to work well in my testing though now I see that you can design to not have this if you make use of `SyncManager.requestedBlocks` map. Though since you'll now need to have a lock around the map to prevent async access.

2025-06-03 08:21 UTC, kcalvinalvin commented on netsync/manager.go
> +func (sm *SyncManager) ConnectedPeers() (<-chan query.Peer, func(), error) {
I named it this because we use this function to meet the interface for `query.WorkManager`. Kinda weird to pass in `SubscribePeers` to meet the interface for `ConnectedPeers` imo.

How about naming the other `ConnectedPeers` in main to `SubscribePeers`?

2025-06-04 07:16 UTC, kcalvinalvin commented on peer/peer.go
> +	return p.quit
You can't close a receive-only channel so it should be fine right? I checked and I'm now allowed to compile the file.

![image](https://github.com/user-attachments/assets/96167e2e-9c72-4ea3-9473-db2c715afc02)

2025-06-04 07:21 UTC, kcalvinalvin commented on netsync/manager.go
> +		if sm.chainParams != &chaincfg.RegressionNetParams {
Ok so this code doesn't exist anymore but it's something that's already existed in the code so I think it's out of the scope for this PR.

2025-06-04 07:49 UTC, kcalvinalvin commented on netsync/manager.go
> +		if err != nil {
I don't think they can since we ignore blocks that we never requested during headers-first but I'll add a test to make sure it does not fail.

2025-06-04 08:03 UTC, kcalvinalvin commented on netsync/manager.go
> -	delete(state.requestedBlocks, *blockHash)
Since we specifically process blocks that are only in the headers chain that we've verified, I don't think this is a risk.

Also, even if we didn't have this check the orphan blocks will get removed after orphan expiration so we're safe from oom attacks.

2025-06-04 08:07 UTC, kcalvinalvin commented on netsync/manager.go
> +				sm.fetchHeaderBlocks()
Not quite.

This branch specifically checks for block headers that we may already have if the sync peer disconnects off of us while downloading headers or blocks.

This lets us avoid downloading extra headers.

2025-06-04 08:09 UTC, kcalvinalvin commented on netsync/manager.go
>  		peer.AddKnownInventory(iv)
Hmm I think this was part of an older code that didn't return from `handleInvMsg()` when headersFirstMode was active.

2025-06-04 08:12 UTC, kcalvinalvin commented on netsync/manager.go
> +		}
> Currently, this section of code panics whenever ANY block (not just checkpoint blocks) fails validation in headers-first mode.

Yes this is the correct behavior since headers-first is based off of checkpoints in btcd.

2025-08-05 04:29 UTC, kcalvinalvin commented on netsync/manager.go
> +	maxInFlightBlocksPerPeer = 32
It could but:

1: I'm not sure having more options is good for the end user. Especially since most don't even know about the utxo caching.
2: I'll leave further improvements for later PRs.

2025-08-05 04:31 UTC, kcalvinalvin commented on netsync/manager.go
> +	blockDownloadWindow = 1024
So I did shrink this down to 256 blocks which would mean 1GB in the absolute worst case (probably won't ever happen since 4MB blocks need to be specially crafted) and 512MB in the average case where blocks are 2MB.

I think this does address the concerns of btcd taking up too much memory and I'll leave futher improvements for later PRs.

2025-08-05 04:31 UTC, kcalvinalvin commented on netsync/manager.go
> +	sm.queuedBlocks[*blockHash] = bmsg
https://github.com/btcsuite/btcd/pull/2226#discussion_r2253079483

2025-08-05 04:32 UTC, kcalvinalvin commented on netsync/manager.go
> -	// When in headers-first mode, if the block matches the hash of the
Addressed in the latest commit

2025-08-05 04:32 UTC, kcalvinalvin commented on netsync/manager.go
> +// handleBlockMsgInHeadersFirst handles block messages from all peers when the
Addressed in the latest commit

2025-08-05 04:34 UTC, kcalvinalvin commented on peer/peer.go
> +				case <-p.quit:
Addressed in the latest commit

2025-08-05 07:35 UTC, kcalvinalvin commented on netsync/manager.go
> +	if !sm.current() && !isSyncCandidate {
Been addressed in previous commits

2025-08-05 07:36 UTC, kcalvinalvin commented on peer/peer.go
> +// SubscribeRecvMsg adds a OnRead subscription to the peer.  All bitcoin
Been addressed in previous commits

2025-08-05 07:36 UTC, kcalvinalvin commented on peer/peer.go
> +// recvMsgsubscription is two channels for a subscriber of recevied messages.
Addressed in previous commits

2025-08-05 07:37 UTC, kcalvinalvin commented on netsync/manager.go
> +// fashion to avoid hv
Addressed as this no longer exists. Replaced with disconnectPeerMsg

2025-08-05 07:37 UTC, kcalvinalvin commented on netsync/manager.go
> +	// We have no more blocks we're expecting from heres so we're finished.
Already addressed in previous commits

2025-08-05 07:38 UTC, kcalvinalvin commented on netsync/manager.go
> +// handleResponse returns that the progress is progressed and finished if the
Addressed in previous commits.

2025-08-05 07:38 UTC, kcalvinalvin commented on netsync/manager.go
> +	// to be fetch from the current best tip.  This number limits the memory
Addressed in previous commits

2025-08-05 07:39 UTC, kcalvinalvin commented on netsync/manager.go
> +	for i, sub := range sm.peerSubscribers {
Addressed in previous commits

2025-08-05 07:41 UTC, kcalvinalvin commented on netsync/manager.go
>  		peer.AddKnownInventory(iv)
No longer the case and we return early if we're in headers-first mode.

2025-08-05 07:42 UTC, kcalvinalvin commented on netsync/manager.go
> +			sm.requestedBlocks = make(map[chainhash.Hash]struct{})
No longer the case as this code has been removed

2025-08-05 08:00 UTC, kcalvinalvin commented on netsync/manager.go
> +		if err != nil {
So I wasn't thinking ahead when I said I'll write a test for this because it's really hard to write a test for this.

But I'm confident that this is safe since:
1: We ignore blocks from peers we aren't connected to.
2: We do not process blocks that aren't based off the headers that we've already downloaded and verified.

2025-08-05 08:13 UTC, kcalvinalvin commented on netsync/manager.go
> +		//
The logic for `choose a sync candidate` is now handled by `returnBestPeer`.
The logic for `in headers-first mode, request headers from the candidate` is now handled by `startHeadersFirstSync`.

The remaining logic for `in normal mode, request blocks from the candidate` remains in startSync.

2025-08-05 08:14 UTC, kcalvinalvin commented on netsync/manager.go
> +		var locator blockchain.BlockLocator
No longer an issue to due refactoring out the logic into different functions.

https://github.com/btcsuite/btcd/pull/2226#discussion_r2253513936

2025-08-05 13:06 UTC, moawnallah commented on netsync/manager.go
> +	blockDownloadWindow = 1024
> So I did shrink this down to 256 blocks which would mean 1GB in the absolute worst case (probably won't ever happen since 4MB blocks need to be specially crafted) and 512MB in the average case where blocks are 2MB.
> 
> I think this does address the concerns of btcd taking up too much memory and I'll leave futher improvements for later PRs.

Reducing the scope of development on first iteration SGTM

2025-08-05 13:07 UTC, moawnallah commented on netsync/manager.go
> +	maxInFlightBlocksPerPeer = 32
> It could but:
> 
> 1: I'm not sure having more options is good for the end user. Especially since most don't even know about the utxo caching. 2: I'll leave further improvements for later PRs.

Sounds good! We can iterate on this later 👍

2025-08-11 05:27 UTC, kcalvinalvin commented
Updated the neutrino library to commit `9bf820ee5929b7547ec98c2bb7303bb129777563`. I'll update it again if the preferred way to update it is to release a new verison and point to that neutrino lib.

2025-09-08 07:45 UTC, yyforyongyu commented on netsync/manager.go
> +	// maxInFlightBlocks is the maximum number of blocks per peer that
```suggestion
	// maxInFlightBlocksPerPeer is the maximum number of blocks per peer that
```

2025-09-08 07:45 UTC, yyforyongyu commented on netsync/manager.go
> +	// to be fetched from the current best tip.  This number limits the memory
```suggestion
	// to be fetched from the current best tip. This number limits the memory
```

2025-09-08 07:53 UTC, yyforyongyu commented on netsync/manager.go
> +	blockDownloadWindow = 256
Given that this will use 1 GB of RAM we def should make these configurable in a follow up PR.

2025-09-08 08:24 UTC, yyforyongyu commented on netsync/manager.go
> +	if !ok {
Can you explain why it's ok to drop other msgs here?

2025-09-08 08:55 UTC, yyforyongyu commented on netsync/manager.go
> +	segwitActive, err := sm.chain.IsDeploymentActive(chaincfg.DeploymentSegwit)
we should add a field `segwitActive` to `SyncManager` and perform this check inside `New`, checking it here and silence the error is bad - if `startSync` fails, the `SyncManager` enters a state where it has no sync peer, and the stall detector is useless due to `sm.syncPeer` being nil. The only way to recover is for a new peer to connect or for an existing peer to disconnect.

2025-09-08 09:02 UTC, yyforyongyu commented on netsync/manager.go
> +			delete(sm.peerSubscribers, sub)
nit: can we move the cleanup to other places and keep the method sticking to [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)?

2025-09-08 09:05 UTC, yyforyongyu commented on netsync/manager.go
> +		if peer.Addr() == peerAddr {
nit: check `if peer.Addr() != peerAddr` instead

2025-09-08 09:08 UTC, yyforyongyu commented on netsync/manager.go
> +				sm.syncPeer, _ = sm.returnBestPeer(true)
why are we silencing the error here? And the `sm.syncPeer` could be set to nil, and the sync process will be stalled?

2025-09-08 09:25 UTC, yyforyongyu commented on netsync/manager.go
> +func (sm *SyncManager) ConnectedPeers() (<-chan query.Peer, func(), error) {
I checked the `query.WorkManager` and didn't find an interface method named `ConnectedPeers()` tho

2025-09-08 09:26 UTC, yyforyongyu commented on netsync/manager.go
> +func (sm *SyncManager) ConnectedPeers() (<-chan query.Peer, func(), error) {
also no need to return `error` given it's always nil.

2025-09-08 09:31 UTC, yyforyongyu commented on netsync/manager.go
> +		query.NumRetries(0),
So retrying is disabled? why is that?

2025-09-09 03:52 UTC, yyforyongyu commented on netsync/manager.go
> +		log.Warnf("failed to check if we already have block %v. %v",
This should be `Errorf`

2025-09-09 03:53 UTC, yyforyongyu commented on netsync/manager.go
> +			"headers-first mode", bmsg.block.Hash())
```suggestion
			"headers-first mode", blockHash)
```

2025-09-09 03:54 UTC, yyforyongyu commented on netsync/manager.go
> +		Hash: *bmsg.block.Hash(),
```suggestion
		Hash: blockHash,
```

2025-09-09 04:16 UTC, yyforyongyu commented on netsync/manager.go
> +	firstNodeEl := sm.headerList.Front()
I think this `for` loop is a bit complex and inefficient. Current flow,
  1. A block arrives.
  2. It is unconditionally added to the `sm.queuedBlocks` map.
  3. A complex for loop is then initiated to iterate from the start of the headerList to see if the block we just added (or any other block in the queue) can now be processed.

A better flow,
  1. A block arrives.
  2. Check if this block is the one specific block we are currently waiting for (i.e., does its hash match the hash at the front of the headerList?).
  3. If it is not the block we are waiting for, add it to the `sm.queuedBlocks` map for later.
  4. If it is the block we are waiting for, process it immediately. Then, start a loop to check if the next block in the sequence is now waiting in the queue, and continue processing as long as possible.

2025-09-09 04:35 UTC, yyforyongyu commented on netsync/manager.go
> +		if err != nil {
> We do not process blocks that aren't based off the headers that we've already downloaded and verified.

Yeah I think that's correct.

2025-09-09 04:57 UTC, yyforyongyu commented on netsync/manager.go
> +			// validation.  If it did, then the binary is likely corrupted.
> If it did, then the binary is likely corrupted.

I don't think it's valid. I mean, if the binary is corrupted, why doesn't the attacker just modify the panic too? I think most likely there is a bug in `ProcessBlock`, in which case it makes sense to shut down.

We will need more explicit docs explaining why it's ok to panic, or better, use critical logs here to gracefully shut down in case there are db operations. It will be confusing at first glance as we are processing external data sent from an untrusted peer, yet it seems like the peer can cause us to crash - we should mention that because we have checkpoints, the block hash is already checked and it's what we requested, the only failure here is a bug in `ProcessBlock`, in which case we should fail fast.

2025-09-09 05:03 UTC, yyforyongyu commented on netsync/manager.go
> +			sm.syncPeer.Addr(), err)
This method is a bit long and complicated, I would favor breaking it down so it's easier for the reviewers, sth like,
```go
// handleBlockMsgHeadersFirst is the main entry point for a received block
// during headers-first sync. It coordinates queuing the block and then
// attempting to process any available sequential blocks.
func (sm *SyncManager) handleBlockMsgHeadersFirst(bmsg *blockMsg) error {
	blockHash := bmsg.block.Hash()

	// Step 1: Add the new block to our queue of out-of-order blocks.
	// A peer that sends a block we already have is misbehaving.
	// NOTE: This check is not perfect due to race conditions but is a
	// reasonable first-pass filter.
	if _, exists := sm.queuedBlocks[*blockHash]; exists {
		log.Warnf("Peer %s sent duplicate block %v in headers-first mode. "+
			"Disconnecting.", bmsg.peer, blockHash)
		bmsg.peer.Disconnect()
		return fmt.Errorf("peer %s sent duplicate block %v", bmsg.peer, blockHash)
	}
	sm.queuedBlocks[*blockHash] = bmsg
	sm.lastProgressTime = time.Now()

	// Step 2: Attempt to process any sequential blocks that are now available.
	// The peer that delivered the block which unlocks processing is passed
	// for attribution in case of errors.
	if err := sm.processQueuedBlocks(bmsg.peer); err != nil {
		// A validation or processing error occurred. The responsible peer has
		// already been disconnected by the helper function. We just need to
		// propagate the error so the sync state can be reset.
		return fmt.Errorf("failed to process queued blocks: %w", err)
	}

	// Step 3: If the pipeline is running low, request more blocks.
	// This is now clean and separate from the processing logic.
	if sm.shouldFetchMoreBlocks() {
		sm.fetchHeaderBlocks()
	}

	return nil
}
```

2025-09-09 05:08 UTC, yyforyongyu commented on peer/peer.go
> +	return p.quit
yeah correct - TIL

2025-09-09 05:14 UTC, yyforyongyu commented on peer/peer.go
> +			go func(subscription recvMsgsubscription,
Just wanna note that this will create many short-lived goroutines given it spawns a new goroutine for every single message delivered to every single subscriber - we may consider buffering the subscriber's channel, tho non-blocking.

2025-09-16 07:15 UTC, kcalvinalvin commented
Ok so maybe I should've said it earlier but I don't really think this code is good.

The query package manager isn't really fit for the use in btcd because of a few reasons:

1: You can't tell which peer returned which block from the netsync package, making it hard to tell which peers to punish. The PR on the query package was meant to address this but it really is a hack and very ugly.

2: netsync package now has two different routes in where the block is received. The current path from the peer package in which the blocks are queued with `QueueBlock`. The extra path added by the query package. This makes it hard to reason about the code since you're receiving the same block in two different parts of the code.

3: The aforementioned (2) results in a lot of exceptions in the code since it's receiving the block in two different code paths. This results in a code bloat and I don't really see this as maintainable.

For the above reasons, I can't really see how this code would be manageable going forward. I myself don't really see this code as something good to have in the btcd codebase. I can't stand behind this code.

Sorry for all the time wasted on this. I tried to make it work but I don't think this is architecturally sound. I'll push a different PR soon.

2025-09-16 07:15 UTC, closed without merging