multi: introduce v2transport and implement BIP324
btcsuite/btcd pull request #2260
Opened 2024-10-02 16:10 UTC by Crypt-iQ

Depends on https://github.com/btcsuite/btcd/pull/2219

This PR implements the [BIP324 encrypted version 2 handshake](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki). The service flag is added to the list of supported services so that btcd will optimistically try to make v2 connections.

2024-10-07 23:41 UTC, saubyk commented
cc: @kcalvinalvin for review

2024-10-12 14:03 UTC, kcalvinalvin commented
Haven’t yet taken a look at other parts in details but seems like the PR is missing `NODE_P2P_V2` signaling support. Not sure if this part of the code was out of scope for the PR but

Should add

```

SFNodeP2PV2 = 1 << 11

```

here: https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/wire/protocol.go#L72-L105

And other necessary code at:

https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/server.go#L2723-L2743

2024-10-15 15:15 UTC, kcalvinalvin reviewed
Initial round of review. Went through BIP324 and compared the flows and the pseudocode provided in the BIP with the code in `transport.go` and `chacha.go`

2024-11-02 07:34 UTC, litecomb commented
WriteV2MessageN should allow specify the garbage []byte, if nil default garbage is used
ReadV2MessageN should allow reading the garbage []byte

Rationale: this will permit custom nonstandard packets communication in the protocol, while still being compatible with bitcoin.

2024-11-09 12:57 UTC, litecomb commented
It would be great if v2transport wasn't promoted to go module to ease reviewing

2025-03-26 19:55 UTC, Crypt-iQ commented on v2transport/transport.go
> +
I believe this is implemented on the receiving side

2025-03-26 19:59 UTC, Crypt-iQ commented
Pushed up the latest set of changes, will work on addressing the comments. Inbound v2 connections now work. The one thing that is not implemented that bitcoind implements and the BIP text [recommends](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki#signaling-specification) we implement is optimistically reconnecting via v1 if an outbound v2 connection failed.

2025-03-26 20:09 UTC, Crypt-iQ commented on v2transport/transport.go
> +
I think this is implemented properly because we'll continue to parse the 16 bytes and eventually call `CompleteHandshake` which will compare the already-parsed 16 bytes and error out with `errWrongNetV1Peer`. Ideally it would have a test though.

2025-03-27 15:01 UTC, Crypt-iQ commented on v2transport/transport.go
> +		receivedPrefix = make([]byte, 0)
I've pre-allocated now, but I think this case should actually be removed?

2025-03-27 15:30 UTC, Crypt-iQ commented on v2transport/transport.go
> +	if !initiating && bytes.Equal(ellswiftTheirs[4:16], v1Prefix[4:16]) {
I think this is fine as-is? Maybe I'm misunderstanding, but I think we'll disconnect the node if they have the wrong network magic? Ideally this would also have a test.

2025-03-27 15:37 UTC, Crypt-iQ commented on v2transport/transport.go
> +		encPacket, _, err := p.V2EncPacket(decoyContent, aad, false)
Yup, nice catch. This code is currently unused but should use a test.

2025-03-27 15:39 UTC, Crypt-iQ commented on v2transport/transport.go
> +	_, _, err = p.V2EncPacket(transportVersion, aad, false)
This needs to be `aad` in case we haven't sent decoy packets which we don't currently

2025-03-27 15:42 UTC, Crypt-iQ commented on peer/peer.go
> +		atomic.AddUint64(&p.bytesReceived, uint64(n))
good catch!

2025-03-27 16:03 UTC, Crypt-iQ commented on v2transport/transport.go
> +	for i := 0; i < 4096; i++ {
Added a comment, I think this should actually be `4095`

2025-03-27 16:37 UTC, Crypt-iQ commented on v2transport/transport.go
> +	ignoreNum <<= ignoreBitPos
Done, let me know if this is what you had in mind

2025-03-27 16:41 UTC, Crypt-iQ commented on v2transport/transport.go
> +	p.sentGarbage = make([]byte, garbageLen)
Yup, now asserting that it's <= 4095 bytes

2025-03-27 16:43 UTC, Crypt-iQ commented on v2transport/chacha.go
> +	binary.LittleEndian.PutUint64(initialNonce[4:12], uint64(numRekeys))
I think this was used in an earlier iteration of the code, removed.

2025-03-27 16:44 UTC, Crypt-iQ commented on v2transport/transport.go
> +	encPacket := make([]byte, 0)
Done

2025-03-27 16:58 UTC, Crypt-iQ commented on v2transport/chacha.go
> +	f.cipher.XORKeyStream(dst, text)
Yeah, we don't actually need `block_counter` here. I implemented it with `block_counter` and found that it actually served no use since the `XORKeyStream` handles the keystream bytes for us.

2025-03-28 03:03 UTC, Roasbeef commented on v2transport/chacha.go
> +// FSChaCha20 ...
Missing `godoc` comments.

2025-03-28 03:04 UTC, Roasbeef commented on v2transport/chacha.go
> +// FSChaCha20 ...
Should mention the purpose of these wrappers. Eg: this one is used to encrypt the lengths of all packets.

2025-03-28 03:06 UTC, Roasbeef commented on v2transport/chacha.go
> +		binary.LittleEndian.PutUint64(nonce[4:12], numRekeys)
Hmm, I don't see a section of the BIP that matches this.

2025-03-28 03:09 UTC, Roasbeef commented on v2transport/transport.go
> +	sendGarbageTerm []byte
IIUC this is always 16 bytes? So can make this a fixed size array.

2025-03-28 03:10 UTC, Roasbeef commented on v2transport/transport.go
> +func (p *Peer) createV2Ciphers(ecdh_secret []byte, initiating bool,
ecdh_secret -> ecdhSecret

2025-03-28 03:14 UTC, Roasbeef commented on v2transport/transport.go
> +	//     To achieve forward secrecy we must wipe the key material used to initialize the ciphers:
I think in go we can mainly w/ best effort basis:
  * use something like `mlock` to prevent the secret data from swapping to disk 
  * make functions to zero out bytes either by doing each byte, or setting the pointer to an empty value
      * optionally force a GC at this point 

Can be wroth checking if the crypto stuff in the stdlib does anything fancy here.

2025-03-28 03:14 UTC, Roasbeef commented on v2transport/transport.go
> +	//     To achieve forward secrecy we must wipe the key material used to initialize the ciphers:
Looks like there's this issue: https://github.com/golang/go/issues/21865

2025-03-28 03:15 UTC, Roasbeef commented on v2transport/transport.go
> +	p.privkeyOurs, p.ellswiftOurs, err = btcec.EllswiftCreate()
Thought this was in a sub-package? If not, we should move it to one.

2025-03-28 03:20 UTC, Roasbeef commented on v2transport/transport.go
> +
AFAICT, it's a bit hidden in the pseudo code, it makes V1 prrefix which includes the network magic, see `complete_handshake`: 
> NETWORK_MAGIC = b'\xf9\xbe\xb4\xd9' # Mainnet network magic; differs on other networks.
> V1_PREFIX = NETWORK_MAGIC + b'version\x00\x00\x00\x00\x00'

>     if not initiating and ellswift_theirs[4:16] == V1_PREFIX[4:16]:
>         # Looks like a v1 peer from the wrong network.
>         disconnect(peer)

2025-03-28 03:21 UTC, Roasbeef commented on v2transport/transport.go
> +	if !initiating && bytes.Equal(ellswiftTheirs[4:16], v1Prefix[4:16]) {
This matches the logic in `complete_handshake` for the psuedo code in the BIP.

2025-03-28 03:22 UTC, Roasbeef commented on v2transport/transport.go
> +func (p *Peer) V2EncPacket(contents []byte, aad []byte, ignore bool) ([]byte,
Would be good to create some basic benchmarks for:
  * handshake creation
  * handshake complete 
  * v2 encrypt 
  * v2 decrypt 

Just so we can get an ideal re the current cpu/memory utilization.

2025-03-28 03:25 UTC, Roasbeef commented on peer/peer.go
> +	} else if partial {
?

2025-03-28 03:28 UTC, Roasbeef commented on peer/peer.go
> +		// TODO: Change garbageLen to be random.
So just a random 12 byte int?

2025-03-28 13:39 UTC, Crypt-iQ commented on btcec/ellswift.go
> +// TODO: Rewrite these to avoid new(FieldVal).Add(...) usage?
I forget what I meant with this comment, I think I wanted to see if it was possible to initialize the `FieldVal` with the value instead of calling `new` followed by `Add`?

2025-03-28 14:12 UTC, Crypt-iQ commented on btcec/ellswift.go
> +func XSwiftEC(u, t *FieldVal) (*FieldVal, error) {
I double-checked and it looks weird, but this is the proper code for `XSwiftEC` from the BIP. Just curious, what made you think that they were combined here?

2025-03-28 14:13 UTC, Crypt-iQ commented on btcec/ellswift.go
> +		if _, found := liftX(new(FieldVal).Add(x).Add(u).Negate(2)); found {
The `2` is the magnitude of the value we are negating -- I think this is correct based on my reading of the `Negate` godoc.

2025-03-28 14:24 UTC, Crypt-iQ commented on btcec/ellswift.go
> +	y := new(FieldVal).Add(x).Square().Mul(x).AddInt(7)
I thought so initially, but I don't think so in this case? From my reading of the godocs on magnitude in the various `FieldVal` functions, `isOnCurve` needs to normalize because `Equals` is being called which requires both inputs to be normalized. With this function `isXOnCurve`, I don't think we need to normalize since none of the used `FieldVal` functions require us to normalize unless the input magnitude is too large.

2025-03-28 14:48 UTC, Crypt-iQ commented on btcec/ellswift.go
> +	if !y.Negate(1).Normalize().IsOdd() {
Ah yeah, this does rely on mutation, @kcalvinalvin pointed out that we can just use `DecompressY` instead. I'll change the code to reflect that

2025-03-28 14:52 UTC, Crypt-iQ commented on btcec/ellswift.go
> +	if !y.Negate(1).Normalize().IsOdd() {
Hmm, on second thought. IIUC `DecompressY` also mutates `resultY` and the reason we want `liftX` is that it returns `PublicKey`. Should I still change this code to use `DecompressY`?

2025-03-28 14:57 UTC, Crypt-iQ commented on v2transport/chacha.go
> +// FSChaCha20 ...
Done

2025-03-28 17:56 UTC, Crypt-iQ commented on v2transport/chacha.go
> +		binary.LittleEndian.PutUint64(nonce[4:12], numRekeys)
This is an implementation detail specific to the golang `chacha20` library. We don't get the keystream bytes directly and instead have to use `XORKeyStream` and xor it with empty `[N]byte` to output the keystream bytes. The only time we need to change the nonce here is during each re-keying interval as o/w it stays the same.

2025-03-28 18:07 UTC, Crypt-iQ commented on v2transport/transport.go
> +	sendGarbageTerm []byte
Yup

2025-03-28 19:40 UTC, Crypt-iQ commented on v2transport/transport.go
> +	p.privkeyOurs, p.ellswiftOurs, err = btcec.EllswiftCreate()
Will move

2025-03-28 21:20 UTC, Crypt-iQ commented on peer/peer.go
> +	} else if partial {
This is used for when we expect a v2 inbound connection but instead receive a v1 version message. In this case, we've already read some of the v1 version header and need to process the rest of it. Without this, the v2->v1 inbound downgrade doesn't work properly.

2025-03-28 21:21 UTC, Crypt-iQ commented on peer/peer.go
> +		// TODO: Change garbageLen to be random.
I'm not sure why I chose it to be `1` here, it can instead be `0` I think. The garbage here is limited to `4095` bytes.

2025-03-28 23:07 UTC, Roasbeef commented
We should likely have a config to disabled the new behavior as well.

2025-03-28 23:21 UTC, Roasbeef commented on peer/peer.go
> +	} else if partial {
Hmm, ok will examine this relevant area of the BIP further. 

Can we add a comment here explaining the rationale here a bit?

2025-04-22 22:35 UTC, Roasbeef commented on server.go
> +		// TODO: Determine _how_ to trigger a reconnect that does not use v2
I think we can annotate `serverPeer` or wrap it in a struct that adds extra context. 

Then when we go to handle the done peer: https://github.com/btcsuite/btcd/blob/85de89db5b5dd6399e7ff8571ebbf6baece7606b/server.go#L1832-L1842

We annotate a new map (one route) that tracks downgrade attempts that need to be achieved. When we connect to the peer, and go to make a new peer struct, we check that map, and based on that value we set the v2 option in the config.

2025-05-03 15:57 UTC, Crypt-iQ commented
Pushed up a patch that implements the reconnection logic. It is not currently working on mainnet, I believe it is because I am catching `EOF` instead of some of the other read errors like "use of closed network connection".

2025-05-04 16:32 UTC, Crypt-iQ commented
Latest set of changes allow the outbound v2->v1 connection downgrade to work properly. Have run this on mainnet and btcd is able to reconnect when an outbound v2 fails.

2025-05-05 19:45 UTC, Roasbeef requested changes

2025-05-05 19:45 UTC, Roasbeef commented on peer/peer.go
> +	// TODO: Modify this so that we can downgrade certain peers.
WIP TODO?

2025-05-05 19:45 UTC, Roasbeef commented on peer/peer.go
> +		if err := p.V2Transport.InitiateV2Handshake(0); err != nil {
Let's make this a constant somewhere so this section is more readable.

2025-05-05 19:45 UTC, Roasbeef commented on peer/peer.go
> +		if err := p.V2Transport.InitiateV2Handshake(0); err != nil {
Also why this change?

2025-05-05 19:45 UTC, Roasbeef commented on server.go
> +	// TODO: Memory leak if outbound target reached and non-persistent peer.
Let's make this into an issue instead? Also what stops of from periodically garbage collecting this? IIUC this map should never have more than outbound target entries

2025-05-05 19:45 UTC, Roasbeef commented on server.go
> +	// TODO: Memory leak if outbound target reached and non-persistent peer.
Can also prob just use `sync.Mutex` to not have to worry as much re critical areas.

2025-05-05 19:45 UTC, Roasbeef commented on server.go
> +	shouldReconnect bool
Why do we need this _and_ the field we added in the prior commit? `ShouldDowngradeToV1`

2025-05-05 19:45 UTC, Roasbeef commented on server.go
> +	peerAddr := c.Addr.String()
Perhaps we should normalize a bit here and _only_ track the IP? IIUC the port would be included here.

2025-05-05 19:45 UTC, Roasbeef commented on server.go
> +		sp.SetShouldReconnect()
See comment above, re just exposing the internal peer method directly.

2025-05-05 19:45 UTC, Roasbeef commented on connmgr/connmanager.go
> +func (cm *ConnManager) Disconnect(id uint64, reconnect bool) {
Is this needed? I think we just actually need to call `Remove`, then we can manually queue the reconnection attempt ourselves.

2025-05-23 03:23 UTC, Roasbeef commented on peer/peer.go
> +		if err := p.V2Transport.InitiateV2Handshake(0); err != nil {
Swapped in to use a proper random garbage length.

2025-05-24 01:45 UTC, Roasbeef approved these changes
LGTM 🎄

Pushed up a few commits to help take this across the finish line.

2025-06-03 02:23 UTC, Crypt-iQ reviewed
Reviewed + tested and it works, ACK 5ab25f3f2bd418fba09325c0f496f56aca03e9a3

I think deployment and cross impl fuzzing will shake out any lingering bugs

2025-06-03 02:23 UTC, Crypt-iQ commented on peer/peer.go
> +		case err != nil:
👍

2025-06-03 23:42 UTC, Roasbeef commented
Have been running this without issue for the past week. Confirmed the downgrade logic works for both inbound and outbound peers. Interop with the only other implementation that supports this BIP (`bitcoind`) also is operational. 

Will merge, then create follow up PRs to update the module tags, before a final PR that'll remove the replace directives from the top level module.

2025-06-03 23:44 UTC, merged