feat: Add testnet4 chain support
btcsuite/btcd pull request #2274
Opened 2024-11-10 16:02 UTC by bullet-tooth

This PR adds support of the Bitcoin testnet version 4 chain (testnet3 is in a way of deprecation).

Reference: https://bips.dev/94/

Testnet4 genesis block: https://mempool.space/testnet4/block/00000000da84f2bafbbc53dee25a72ae507ff4914b867c565be350b0da8bf043

_Also, I have intention to add testnet4 support to btcwallet after this PR_

2024-11-11 18:38 UTC, Roasbeef commented
Looks like we have another here: https://github.com/btcsuite/btcd/pull/2275

Neither that one, nor this one, have any of the new difficulty adjustment algorithm changes.

2024-11-20 22:52 UTC, Roasbeef commented
@bullet-tooth see the BIP: https://bips.dev/94/

2024-12-10 14:52 UTC, guggero commented
If you clean up the PR into a review friendly commit structure, I'll take a look.
Here are some docs to go by: https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md
and https://github.com/lightningnetwork/lnd/blob/master/docs/code_formatting_rules.md.
Those aren't strictly enforced in this project but definitely nice to have if you want review from the lnd team.

2025-01-16 12:26 UTC, guggero requested changes
Thanks for the update.
Still requires quite a bit of formal cleanup before more review time should be put in.

With "review friendly commit structure" I didn't mean squashing everything into a single commit.
Suggestion for commit order:
 - Any comment/typo fixes.
 - Any changes to non-Go files (e.g. `.gitignore`)
 - Add new parameter to `chaincfg` including unit tests.
 - Add `EnforceBip94` flag to parameters.
 - Add changes to `blockchain` package.
 - Add changes to `cmd` package.

2025-01-16 12:26 UTC, guggero commented on blockchain/difficulty.go
> +	// Special difficulty rule for Testnet4
Please use full sentences, including punctuation, for comments. Also, if a comment isn't at the beginning of a block, it's nice to have an empty line before it to have some vertical breathing room.
Finally, `else` is kind of discouraged in Go if it can be written in a different way, as it often leads to less readable code.
So I'd write this the following way:

```go

	// Special difficulty rule for Testnet4
	oldTarget := CompactToBig(lastNode.Bits())
	if c.ChainParams().EnforceBIP94 {
		// Here we use the first block of the difficulty period. This way
		// the real difficulty is always preserved in the first block as
		// it is not allowed to use the min-difficulty exception.
		oldTarget = CompactToBig(firstNode.Bits())
	}
```

Of course the assumption here is that `CompactToBig(lastNode.Bits())` isn't computationally expensive to wanting to avoid calling it twice in the worst case.

2025-01-16 12:26 UTC, guggero commented on blockchain/error.go
> +	ErrTimewarpAttack
nit: missing Godoc comment.

2025-01-16 12:26 UTC, guggero commented on blockchain/validate.go
> +// represented in the blockchain by a transaction with a single input that has
Please revert these. This specifically refer to the chain of blocks, not the package name. IMO "Blockchain" is a marketing term used by people trying to sell you something that isn't Bitcoin.

2025-01-16 12:26 UTC, guggero commented on blockchain/validate.go
> +	}
nit: line length. Also, sounds like this whole block could be extracted into a standalone function. Something like `checkBip94()`.

2025-01-16 12:26 UTC, guggero commented on btcd.go
> +	if cfg.TestNet3 {
Not sure I agree with that whole block.

2025-01-16 12:26 UTC, guggero commented on chaincfg/genesis_test.go
> +	"github.com/stretchr/testify/require"
nit: please sort this with the block below where non-std-lib imports go.

2025-01-16 12:26 UTC, guggero commented on chaincfg/genesis_test.go
> +	if err != nil {
Should use `require.NoError()` and `require.Equal()` for new test code.

2025-01-16 12:26 UTC, guggero commented on chaincfg/params.go
> +	EnforceBIP94 bool
nit: Godoc missing.

2025-01-16 12:26 UTC, guggero commented on chaincfg/params.go
> +	EnforceBIP94:             false,
IMO we don't need to add `false` to the existing params as that's the default value for a boolean.

2025-01-16 12:26 UTC, guggero commented on chaincfg/params.go
> +var TestNet4Params = Params{
nit: missing Godoc params.

2025-01-16 12:26 UTC, guggero commented on chaincfg/params.go
> +	//// Chain parameters
nit: double comment.

2025-01-16 12:26 UTC, guggero commented on cmd/addblock/config.go
> +	TestNet3       bool   `long:"testnet" description:"Use the test network (version 3). Support for testnet3 is deprecated. Consider moving to testnet4 now by using -testnet4"`
nit: remove deprecation comment. Should be out of scope for this PR.

2025-01-16 12:26 UTC, guggero commented on cmd/addblock/config.go
> +	// TODO do we need to use "testnet" dir for testnet4 as well?
We should use a distinct directory, otherwise you couldn't run both on the same computer.

2025-01-16 12:26 UTC, guggero commented on cmd/btcctl/config.go
> +	TestNet3       bool   `long:"testnet" description:"Connect to testnet (version 3). Support for testnet3 is deprecated. Consider moving to testnet4 now by using -testnet4"`
Remove deprecation comment.

2025-01-16 12:26 UTC, guggero commented on cmd/findcheckpoint/config.go
> +	TestNet3       bool   `long:"testnet" description:"Use the test network (version 3). Support for testnet3 is deprecated. Consider moving to testnet4 now by using -testnet4"`
Same here re deprecation.

2025-01-16 12:26 UTC, guggero commented on config.go
> +	TestNet3             bool          `long:"testnet" description:"Use the test network (version 3). Support for testnet3 is deprecated. Consider moving to testnet4 now by using -testnet4"`
And here.

2025-01-16 12:26 UTC, guggero commented on peer/peer.go
> +		// TODO: change to testnet4 because testnet3 will be deprecated soon
Disagree.

2025-02-10 11:26 UTC, humb1t commented
Great work @bullet-tooth - can't wait to see this PR being merged.

2025-02-10 15:56 UTC, closed without merging